name: Branch - Merge to main - Create Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    name: Create deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: PR Desciption
        uses: actions/github-script@v3
        if: ${{ github.event_name == 'pull_request' && github.event.pull_request.merged == true }}
        env:
          pr_desciption: ${{ github.event.pull_request.title }}

      - name: Get temporary token for creating deployment
        id: temp_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.REPO_AUTOMATION_APPLICATION_ID }}
          application_private_key: ${{ secrets.REPO_AUTOMATION_APPLICATION_KEY }}

      - name: Create Deployment
        uses: actions/github-script@v3
        env:
          container_registry: ghcr.io

          app_container_image: 'charliejazz/cicd-aks'
          app_container_version: ${{ github.ref_name }}-${{ github.run_number }}
# create deployment with merged PR name
        with:
          github-token: ${{ steps.temp_token.outputs.token }}
          script: |
            const scriptPath = require('path').resolve('./.github/workflows/scripts/create_deployment.js');
            const createDeployment = require(scriptPath);

            await createDeployment({
              context: context,
              github: github,
              environment: 'prod',
              containerRegistry: process.env.container_registry,
              appContainerImage: process.env.app_container_image,
              appContainerVersion: process.env.app_container_version,
              description: process.env.pr_desciption,
              sha: context.sha,
              head: ${{ github.ref_name }}, //Branch name PR created from
            });

      - name: Create tag
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/${{ github.ref_name }}-${{ github.run_number }}',
              sha: context.sha
            })