name: Deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: 'Azure Secret Name containing the Service Principal Details'
        required: true
        default: 'AZURE_SUBSCRIPTION'
jobs:
  deploy:
    name: Test manual tags
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2

      - name: deploy
        id: deploy
        run: |
          echo ${{ github.ref_name }}
        shell: bash
        